name: qr_service
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  image: ^4.1.3
  qr: ^3.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
